
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
main_project_member = "apps/api"

[tasks.dev]
workspace = false
env = { "RUST_LOG" = "info,sqlx::query=warn" }
command = "cargo"
args = ["run"]

[tasks.db-create]
workspace = false
cwd = "./"
command = "sqlx"
args = ["db", "create"]

[tasks.db-migrate]
workspace = false
cwd = "./"
command = "sqlx"
args = ["migrate", "run"]

[tasks.db-reset]
workspace = false
cwd = "./"
command = "sqlx"
args = ["db", "reset"]

[tasks.docker]
workspace = false
cwd = "./"
command = "docker-compose"
args = ["-f", "docker-compose.yml", "${@}"]

[tasks.docker-api]
workspace = false
cwd = "./apps/api"
command = "docker-compose"
args = [
    "-f",
    "../../docker-compose.yml",
    "-f",
    "docker-compose.app.yml",
    "--env-file",
    "../../.env",
    "${@}",
]

[tasks.schema]
workspace = false
cwd = "./"
command = "cargo"
args = ["run", "--bin", "caster-schema"]

[tasks.integration]
workspace = false
env = { "RUN_MODE" = "test", "RUST_LOG" = "info,sqlx::query=warn", "RUST_TEST_THREADS" = 1, "RUST_BACKTRACE" = 0 }
command = "cargo"
args = ["test", "--", "--nocapture", "--ignored", "${@}"]

[tasks.integration-ci]
workspace = false
env = { "RUN_MODE" = "ci", "RUST_LOG" = "info,sqlx::query=warn", "RUST_TEST_THREADS" = 1 }
command = "cargo"
args = ["test", "--", "--nocapture", "--ignored"]
