name: Cache App
description: Cache Rust Cargo and the target directory based on a hash of the Cargo.lock.

runs:
    using: composite
    steps:
        - name: Cache Cargo
          uses: actions/cache@v2
          with:
              path: /home/runner/.cargo
              key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
              restore-keys: |
                  cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-
                  cargo-home-${{ runner.os }}-

        - name: Cache target
          uses: actions/cache@v2
          with:
              path: target
              key: rust-target-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}-${{ github.sha }}
              restore-keys: |
                  rust-target-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}-
                  rust-target-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}-
                  rust-target-${{ runner.os }}-
