[package]
name = "caster-api"
version = "0.1.0"
authors = ["Brandon Konkle <brandon@konkle.us>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
async-graphql = { version = "3.0", features = ["chrono"] }
async-graphql-warp = "3.0"
caster-auth = { path = "../../libs/auth" }
caster-shows = { path = "../../libs/shows" }
caster-users = { path = "../../libs/users" }
caster-utils = { path = "../../libs/utils" }
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
hyper = "0.14"
hyper-tls = "0.5"
log = "0.4"
once_cell = "1.9"
pretty_env_logger = "0.4"
sea-orm = { version = "0.6", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "mock",
], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
sqlx = { version = "0.5", features = [
    "chrono",
    "json",
    "macros",
    "migrate",
    "postgres",
    "runtime-tokio-rustls",
    "uuid",
] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"

[dev-dependencies]
fake = { version = "2.4", features = ['derive', 'chrono', 'http', 'uuid'] }
hyper = "0.14"
hyper-tls = "0.5"
jsonpath_lib = "0.3.0"
mockall = "0.11"
rand = "0.8"
