[package]
name = "caster-api"
version = "0.1.0"
authors = ["Brandon Konkle <brandon@konkle.us>"]
edition = "2021"

[dependencies]
async-graphql = { version = "2.10.8", features = ["chrono"] }
async-graphql-warp = "2.10.8"
caster-shows = { path = "../../libs/shows" }
caster-users = { path = "../../libs/users" }
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"
log = "0.4"
pretty_env_logger = "0.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.68"
sqlx = { version = "0.5", features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "migrate",
    "uuid",
    "chrono",
    "json",
] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"

[dev-dependencies]
fake = { version = "2.4", features = ['derive', 'chrono', 'http', 'uuid'] }
hyper = "0.14"
hyper-tls = "0.5"
jsonpath_lib = "0.3.0"
lazy_static = "=1.4.0"
mockall = "0.10.2"
rand = "0.8"
testcontainers = "0.12.0"
