name: CI # Continuous Integration

on:
    pull_request:
        paths-ignore:
            - "**.md"
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        name: Test Suite
        runs-on: ubuntu-latest
        env:
            RUSTFLAGS: -D warnings
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  fetch-depth: 0

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: llvm-tools-preview

            - uses: davidB/rust-cargo-make@v1

            - uses: Swatinem/rust-cache@v2

            - name: Install nextest
              uses: taiki-e/install-action@nextest

            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Check formatting
              run: cargo make format

            - name: Clippy check
              run: cargo make lint

            - name: Run Unit Tests
              run: cargo make cov-ci

            - name: Upload coverage data to codecov
              uses: codecov/codecov-action@v3
              with:
                  files: lcov.info

    test:
        name: Integration Test
        runs-on: ubuntu-latest
        needs: check
        env:
            DATABASE_HOSTNAME: localhost
            DATABASE_USERNAME: caster
            DATABASE_PASSWORD: caster
            DATABASE_NAME: caster_rust_test
            DATABASE_PORT: 1701
            DATABASE_URL: postgresql://caster:caster@localhost:1701/caster_rust_test
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - uses: davidB/rust-cargo-make@v1

            - uses: Swatinem/rust-cache@v2

            - uses: ./.github/workflows/actions/setup-docker

            - name: Run docker-compose
              run: docker-compose -f docker-compose.yml up -d

            - name: Install SQLx CLI
              uses: baptiste0928/cargo-install@v2
              with:
                  crate: sqlx-cli
                  args: --no-default-features --features rustls,postgres
                  version: latest

            - name: Create Database
              run: cargo make db-create

            - name: Migrate Database
              run: cargo make db-migrate

            - name: Run Integration Tests
              run: cargo make integration-ci
